2024-02-21 20:02:47,865 - 14584-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x037C4910>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 20:02:47,866 - 14584-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x037C4C58>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 20:02:47,866 - 14584-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03803D48>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 20:02:47,866 - 14584-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:380] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-21 20:03:33,414 - 14428-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03B848E0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 20:03:33,414 - 14428-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03B84BB0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 20:03:33,415 - 14428-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03BC3CA0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 20:03:33,415 - 14428-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:380] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-21 20:33:03,830 - 5308-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x037E4970>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 20:33:03,830 - 5308-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x037E4C40>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 20:33:03,831 - 5308-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03824D18>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 20:33:03,831 - 5308-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:378] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-21 21:13:25,626 - 12780-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x036C48E0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 21:13:25,626 - 12780-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x036C4C28>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 21:13:25,627 - 12780-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03704D18>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 21:13:25,627 - 12780-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:378] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-21 21:29:01,158 - 13296-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03D648C8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 21:29:01,159 - 13296-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03D64C28>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 21:29:01,159 - 13296-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03DA5D00>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 21:29:01,159 - 13296-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:378] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-21 21:38:25,117 - 1984-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04DAF028>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 21:38:25,118 - 1984-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04DAF280>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 21:38:25,119 - 1984-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04DAF610>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-21 21:38:25,119 - 1984-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:378] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-22 10:55:41,009 - 2752-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03F948E0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 10:55:41,144 - 2752-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03F94C40>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 10:55:41,145 - 2752-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03FD4D30>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 10:55:41,145 - 2752-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:378] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-22 11:04:02,477 - 3884-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03A03910>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 11:04:02,478 - 3884-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03A03C58>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 11:04:02,478 - 3884-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03A44D48>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 11:04:02,479 - 3884-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:378] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-22 11:09:05,788 - 7396-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03B048C8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 11:09:05,788 - 7396-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03B04C10>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 11:09:05,789 - 7396-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03B44D00>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 11:09:05,789 - 7396-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:378] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-22 15:12:12,411 - 13944-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03694958>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 15:12:12,543 - 13944-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03694CB8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 15:12:12,543 - 13944-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x036D5D78>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 15:12:12,544 - 13944-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:379] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-22 22:40:30,515 - 4856-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:430] - INFO: seckill_by_proc_pool 需登陆后调用，开始扫码登陆
2024-02-22 22:40:31,146 - 4856-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:190] - INFO: 二维码获取成功，请打开京东APP扫描
2024-02-22 22:40:31,699 - 4856-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:221] - INFO: Code: 201, Message: 二维码未扫描，请扫描二维码
2024-02-22 22:40:33,987 - 4856-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:221] - INFO: Code: 201, Message: 二维码未扫描，请扫描二维码
2024-02-22 22:40:36,144 - 4856-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:221] - INFO: Code: 201, Message: 二维码未扫描，请扫描二维码
2024-02-22 22:40:38,298 - 4856-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:221] - INFO: Code: 201, Message: 二维码未扫描，请扫描二维码
2024-02-22 22:40:40,453 - 4856-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:221] - INFO: Code: 201, Message: 二维码未扫描，请扫描二维码
2024-02-22 22:40:42,620 - 4856-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:221] - INFO: Code: 202, Message: 请手机客户端确认登录
2024-02-22 22:40:44,780 - 4856-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:221] - INFO: Code: 202, Message: 请手机客户端确认登录
2024-02-22 22:40:46,945 - 4856-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:221] - INFO: Code: 202, Message: 请手机客户端确认登录
2024-02-22 22:40:49,102 - 4856-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:221] - INFO: Code: 202, Message: 请手机客户端确认登录
2024-02-22 22:40:51,264 - 4856-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:224] - INFO: 已完成手机客户端确认
2024-02-22 22:40:51,829 - 4856-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:278] - INFO: 二维码登录成功
2024-02-22 22:40:52,403 - 4856-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0487F8C8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 22:40:52,403 - 4856-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0487FD60>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 22:40:52,404 - 4856-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0489EF88>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 22:40:52,404 - 4856-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:379] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-22 23:15:13,454 - 16680-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03BD4880>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:15:13,455 - 16680-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03BD4BC8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:15:13,455 - 16680-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03C14CD0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:15:13,456 - 16680-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:379] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-22 23:21:46,740 - 13592-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x044B48E0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:21:46,740 - 13592-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x044B4C28>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:21:46,741 - 13592-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x044F4D18>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:21:46,741 - 13592-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:381] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-22 23:22:14,225 - 7972-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x043C4838>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:22:14,226 - 7972-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x043C4B80>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:22:14,226 - 7972-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04404C88>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:22:14,227 - 7972-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:381] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-22 23:22:30,366 - 13900-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04034868>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:22:30,367 - 13900-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04034BB0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:22:30,367 - 13900-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04074CB8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:22:30,368 - 13900-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:381] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-22 23:28:00,368 - 16396-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03684BE0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:28:00,368 - 16396-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x036C4DD8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:28:00,369 - 16396-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x036C4D48>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-22 23:28:00,369 - 16396-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:381] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 00:02:08,976 - 4908-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03D448F8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:02:08,977 - 4908-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03D44C40>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:02:08,977 - 4908-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03D84D30>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:09:58,768 - 4816-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x042548F8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:09:58,769 - 4816-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04254C40>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:09:58,769 - 4816-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04294D30>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:09:58,770 - 4816-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:383] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 00:14:30,612 - 16900-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x035A48E0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:14:30,613 - 16900-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x035A4C28>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:14:30,613 - 16900-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x035E4D18>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:14:30,614 - 16900-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:383] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 00:16:38,222 - 13952-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x040048C8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:16:38,222 - 13952-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04004C10>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:16:38,223 - 13952-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04044D00>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:16:38,223 - 13952-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:383] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 00:42:38,495 - 5736-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03B55208>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:42:38,496 - 5736-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03B55C10>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:42:38,496 - 5736-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03B95E20>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:42:38,496 - 5736-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:389] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 00:57:21,858 - 1428-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03ED5A90>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:57:21,858 - 1428-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03ED5958>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:57:21,859 - 1428-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:749] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04A06760>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 00:57:21,859 - 1428-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:392] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 01:35:57,496 - 16820-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:661] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03A871F0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 01:35:57,497 - 16820-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:661] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03A874A8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 01:35:57,497 - 16820-MainThread - D:\Python3-9-7\lib\site-packages\urllib3\connectionpool.py[line:661] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03AB4EE0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /chromium-browser-snapshots/Win/588429/chrome-win32.zip
2024-02-23 01:35:57,498 - 16820-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:388] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 01:47:22,095 - 4128-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:337] - INFO: page_title:【京东(JD.COM)-正品低价、品质保障、配送及时、轻松购物！】, page_url【https://www.jd.com/】
2024-02-23 01:47:53,693 - 4128-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:388] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 01:48:47,190 - 14544-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:337] - INFO: page_title:【京东(JD.COM)-正品低价、品质保障、配送及时、轻松购物！】, page_url【https://www.jd.com/】
2024-02-23 01:49:18,835 - 14544-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:388] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 01:58:00,782 - 15072-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:335] - INFO: page_title:【京东(JD.COM)-正品低价、品质保障、配送及时、轻松购物！】, page_url【https://www.jd.com/】
2024-02-23 01:58:32,577 - 15072-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:386] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 02:11:39,595 - 15680-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:335] - INFO: page_title:【京东(JD.COM)-正品低价、品质保障、配送及时、轻松购物！】, page_url【https://www.jd.com/】
2024-02-23 02:12:11,356 - 15680-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:386] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 02:21:56,552 - 3596-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:335] - INFO: page_title:【京东(JD.COM)-正品低价、品质保障、配送及时、轻松购物！】, page_url【https://www.jd.com/】
2024-02-23 02:22:28,191 - 3596-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:386] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 02:39:05,023 - 11308-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:335] - INFO: page_title:【京东(JD.COM)-正品低价、品质保障、配送及时、轻松购物！】, page_url【https://www.jd.com/】
2024-02-23 02:39:36,836 - 11308-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:386] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 02:49:03,399 - 12272-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:335] - INFO: page_title:【京东(JD.COM)-正品低价、品质保障、配送及时、轻松购物！】, page_url【https://www.jd.com/】
2024-02-23 02:49:35,250 - 12272-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:386] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 02:49:54,806 - 16636-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:335] - INFO: page_title:【京东(JD.COM)-正品低价、品质保障、配送及时、轻松购物！】, page_url【https://www.jd.com/】
2024-02-23 02:50:26,791 - 16636-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:386] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 03:03:30,184 - 12916-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:335] - INFO: page_title:【京东(JD.COM)-正品低价、品质保障、配送及时、轻松购物！】, page_url【https://www.jd.com/】
2024-02-23 03:04:01,489 - 12916-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:387] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
2024-02-23 11:15:30,753 - 1692-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:335] - INFO: page_title:【京东(JD.COM)-正品低价、品质保障、配送及时、轻松购物！】, page_url【https://www.jd.com/】
2024-02-23 11:16:02,131 - 1692-MainThread - D:\抢茅台\jd_sckll\QmaoTai\jd_seckill\jd_spider_requests.py[line:386] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！
